### ISSUE TITLE
Make java 8 Date/Time classes (JSR310) first-class citizens in grails

### ISSUE THREAD

**Issue by allnightlong** [grails/grails-core#10141]
It's almost 2 years and a half since java 8 initial release, and still there is no easy way to use Date/Time fields in grails domain classes. 
There are quite a few work to deal with joda time ([issues](https://github.com/grails/grails-core/issues?utf8=%E2%9C%93&q=joda)), but nothing about jsr310.
In the meantime hibernate supported java8 date since [version 5.0](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22hibernate-java8%22), jackson since [version 2.4](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.fasterxml.jackson.datatype%22%20AND%20a%3A%22jackson-datatype-jdk8%22).
I think, that grails as modern web framework should provide first-class support of new Date/Time standard. 

I've started small simple project with little CRUD functionality, and run into several isssues:
### Task List
- [x] Hibernate types should be detected by default, when hibernate-java8 is present in classpath, currently I need to manual assing user-types in application.groovy
- [x] Autotimestamp should work out-of-the box (for example, I could have `OffsetDateTime dateCreated` field, and grails should provide `OffsetDateTime.now()` value,  when I'm saving domain)
- [x] Binding params in controllers: Date/Time objects should respect `grails.databinding.dateFormats` and `@BindingFormat`
- [ ] Provide alternative/overloading to `params.date()` method, that can deal with jsr310 classes
- [x] datePicker should work with Date/Time objects: basic functionality (bind to/from), precision can be detected based on class (show all fields for LocalDateTime, date fields for LocalDate, time fields for LocalTime, and so on for other classes like Year, Month, Month, MonthDay)
- [x] formatDate should accept jsr310 classes, also migration from  slow SimpleDateFormat to [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) should be considered
- [x] JSON (de)serialization should work out-of-the-box (may be  it's groovy-lang related issue)
- [x] Tests should run smoothly (currenlty KeyValueMappingFactory doesn't consider jsr310 classes as ["SIMPLE_TYPES"](https://github.com/grails/grails-data-mapping/blob/2ab84f4940b56f1e59dc2117df8dc9f1655da652/grails-datastore-core/src/main/groovy/org/grails/datastore/mapping/model/MappingFactory.java#L64), and cant deal with them)
- [ ] Provide simple way to pass `java.time.Clock` into framework internals for testing purpose (at least it should be simple to mock Autotimestamped fields)
- [x] JSON views support 

I believe that this list is not complete, but it's something to start.

**Comment by jameskleeh** [comment]
@allnightlong Can you expand on "Hibernate types should be detected by default, when hibernate-java8 is present in classpath, currently I need to manual assing user-types in application.groovy" ? Perhaps provide an example of what isn't working.

**Comment by allnightlong** [comment]
@jameskleeh I'm talking about `hibernate type` <-> `jsr310 type` mapping.

For example, application.groovy in my simple project:
```
import java.time.OffsetDateTime

grails.gorm.default.mapping = {
	/// ... omit for clarity
	'user-type'(type: org.hibernate.type.OffsetDateTimeType, class: OffsetDateTime)
}
```

Another example,  [java8-temporal-grails-plugin](https://github.com/blemoine/java8-temporal-grails-plugin) using jadira framework: https://github.com/blemoine/java8-temporal-grails-plugin/blob/master/README.md#adding-default-type-mapping

But jadira is not actual with hibernate 5 release, which provides native implementations, such as org.hibernate.type.OffsetDateTimeType, org.hibernate.type.ZonedDateTimeType and so on.

**Comment by jameskleeh** [comment]
@allnightlong Regarding hibernate-java8 and user types:

I created an application and defined normal properties (not dateCreated/lastUpdated) with all of the JSR310 types and they actually persisted just fine, however hibernate was persisting them as blobs. After adding the `hibernate-java8` dependency, they were stored in their correct types and it was not necessary for me to add user types. Did you have a different experience?

**Comment by jameskleeh** [comment]
@allnightlong Can you add the grails-java8 plugin to your project and verify if any of the items I have checked off are not working to your expectations? 

`compile "org.grails.plugins:grails-java8:1.1.0.BUILD-SNAPSHOT"`

**Comment by allnightlong** [comment]
@jameskleeh 
After installing this plugin I can confirm that:
1. Out-of-the-box mapping of OffestDateTime is working as expected
2. autoTimestamp is also working OK

On the other hand, I've run into several issues:
1. You did point out, but the plugin doesn't working with grails 3.2.0, but only with 3.2.1+, so I think this should be fixed:
https://github.com/grails-plugins/grails-java8/blob/master/src/main/groovy/org/grails/plugins/web/Java8GrailsPlugin.groovy#L25
2. It seems that some additional configuration is required, to make taglibs work:
`<g:formatDate date="${offsetDateTime}" format="dd.MM.yyyy HH:mm:ss"/>`
fails with such an exception
`ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/posts/show.gsp:40] Error executing tag <g:formatDate>: Unknown class: java.time.OffsetDateTime] with root cause
java.lang.IllegalArgumentException: Unknown class: java.time.OffsetDateTime
	at org.apache.commons.lang.time.FastDateFormat.format(FastDateFormat.java:796)
	at java.text.Format.format(Format.java:157)
	at org.grails.plugins.web.DefaultGrailsTagDateHelper.format(DefaultGrailsTagDateHelper.groovy:66)
	at org.grails.plugins.web.taglib.FormatTagLib$_closure2.doCall(FormatTagLib.groovy:198)
	at org.grails.gsp.GroovyPage.invokeTagLibClosure(GroovyPage.java:410)
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:335)
...`
3. Not sure, that this is the bug, but json marshaling is a little bit awkward: it feels not convention over configuration, but on the contrary noone will use it without additional configuration.
![2016-10-23_19-51-37](https://cloud.githubusercontent.com/assets/360961/19626363/2f6cffba-995a-11e6-8426-c2cd5599ca5a.png)
4. `org.grails.datastore.mapping.model.MappingFactory` currently doesn't supports classes like Instant, Period, Year, YearMonth, MonthDay, etc. Actually I don't use them in my current little pet app, but I can image situation, when I would use them.
![2016-10-23_19-56-57](https://cloud.githubusercontent.com/assets/360961/19626388/e3d848f6-995a-11e6-9561-d72feb299b78.png)

**Comment by jameskleeh** [comment]
@allnightlong 

1. Thanks - fixed
2. Looked like I didn't configure plugin load order correctly. I just tested it now and it is working
3. The JSON marshalling is something we will rely on the Groovy side and most likely won't do anything with in Grails directly
4. Correct - Those 6 classes you have there are the ones we are currently supporting.

**Comment by allnightlong** [comment]
@jameskleeh 
Awesome, thanks for fast response!
Could you, please, build new snapshot, so I can test?

**Comment by jameskleeh** [comment]
@allnightlong The new snapshot should already be available

**Comment by jameskleeh** [comment]
@allnightlong Were you able to test? Version 1.1.0 has been released

**Comment by jameskleeh** [comment]
Other than `params.date` and the Clock feature I never got feedback on, this issue is complete via the grails-java8 plugin.

**Comment by abcfy2** [comment]
Is there any way to set default `sqlType`?

```groovy
class MyDomain {
    OffsetDateTime dateCreated

    static mapping = {
        dateCreated sqlType: 'timestamptz'
    }
}
```

I try to add this to `application.groovy`:

```groovy
import org.hibernate.type.OffsetDateTimeType

grails.gorm.default.mapping = {
    id generator: 'identity'
    'user-type'(type: OffsetDateTimeType, sqlType: 'timestamptz')
}
```

But it's not working, the `dateCreated` field still is `timestamp without timezone`.
