### ISSUE TITLE
Using the render method in a controller without a fully-formed HTML page results in empty response

### ISSUE THREAD

**Issue by ColinHarrington** [grails/grails-core#10150]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided **N/A**
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Grails 3.x application
2. in a controller, render a view `render view: 'showview'` without an `<html>` or `<body>` tag such as:
`<div>View doesn't work</div>`
3. When the  hit the controller and observe

### Expected Behaviour

That the view would be rendered with a 200 http status and the contents of the view rendered to the client.

### Actual Behaviour

The response comes back without any data:
```
curl -v http://localhost:8080/framework/testview
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /framework/testview HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< X-Application-Context: application:development
< Content-Type: text/html;charset=utf-8
< Content-Language: en-US
< Transfer-Encoding: chunked
< Date: Tue, 13 Sep 2016 14:36:29 GMT
< 
* Connection #0 to host localhost left intact
```

### Environment Information

- **Operating System**: Windows/Linux
- **Grails Version:** tested with 3.1.11
- **JDK Version:** java version "1.8.0_45"
- **Container Version (If Applicable):**N/A

### Example Application

* https://github.com/selbin01/templatesvsviews/
* Specifically [this simple example](https://github.com/selbin01/templatesvsviews/blob/master/grails-app/controllers/templatesvsviews/FrameworkController.groovy#L12)

**Comment by jeffbrown** [comment]
This may be a duplicate of https://github.com/grails/grails-core/issues/9810

**Comment by ColinHarrington** [comment]
I did a bit of debugging.  The issue is only triggered when the `render` method is used in the controller.  https://github.com/ColinHarrington/views-examples for some runnable examples.  Basically The `contentType` is being applied to the response directly when the render method is caled and this causes downstream issues when rendering the view.

I have a better PR coming shortly.

**Comment by ColinHarrington** [comment]
fixed as of the 3.1.12 release
