### ISSUE TITLE
Plugin Crypto 2.0 -  unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder

### ISSUE THREAD

**Issue by mrainv** [grails/grails-core#10336]
Thanks for reporting an issue for Grails framework, please review the task list below before submitting the 
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Stack Overflow (http://stackoverflow.com/tags/grails) or Slack (http://slack-signup.grails.org). DO NOT use the issue tracker to ask questions.

### Task List
- [x] Proposed solution
- [x] Modifed crypto 2.0 plugin from target/work in attached zip file

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided (no stack trace, only compile failure)
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. TODO
Install Grails 2.5.5

2. TODO
Add groovy-all-2.4.4.pom next to groovy-all-2.5.5.pom

3. TODO
in grails-2.5.5\lib\org.codehaus.groovy\groovy-all\jars,
Add groovy-all-2.4.4.jar beside groovy-all-2.4.5.jar
Add groovy-all-2.4.4-javadoc.jar beside groovy-all-2.4.5-javadoc.jar
Add groovy-all-2.4.4-sources.jar beside groovy-all-2.4.5-sources.jar

4. TODO, in BuildConfig.groovy
### Expected Behaviour
... what should happen
No compile errors, run-app works as expected

### Actual Behaviour
... what happens instead
| Error 2016-11-29 11:39:03,492 [Thread-11] ERROR compiler.GrailsProjectWatcher  - Compilation Error: startup failed:
C:\git\cin\app\target\work\plugins\crypto-2.0\src\groovy\cr\co\arquetipos\password\PasswordTools.groovy: 7: unable to resolve class org.codehaus.groovy.grails.commons.ConfigurationHolder
 @ line 7, column 1.
   import org.codehaus.groovy.grails.commons.ConfigurationHolder as CH
   ^

1 error

### Environment Information

- **Operating System**: Microsoft Windows [Version 6.1.7601]
- **Grails Version:** Grails version: 2.5.5
- **JDK Version:**
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- **Container Version (If Applicable):** n/a

### Example Application
Add to BuildConfig.groovy (either or both)
compile ':crypto:2.0'   /* OpenPGP Support, including PGP Signatures */
compile ':mail:1.0.7'   /* Send Mail support for a running grails application */

Attempted fix to plugin source file in package cr.co.arquetipos.password
Class named PasswordTools.groovy of plugin crypto 2.0 ( OpenPGP support via BouncyCastle library )
Change line 7, causing "unable to resolve" error
From:
import org.codehaus.groovy.grails.commons.ConfigurationHolder as CH
To:
import grails.util.Holders as CH (from release notes for grails 2.5.5 )
[crypto-2.0.zip](https://github.com/grails/grails-core/files/620252/crypto-2.0.zip)

**Comment by mrainv** [comment]
4. TODO (cont'd) 
In BuildConfig.groovy
add in plugins:
 compile ':crypto:2.0'   /* OpenPGP Support, including PGP Signatures */
compile ':mail:1.0.7'   /* Send Mail support for a running grails application */

**Comment by graemerocher** [comment]
This doesn't seem to be a Grails bug but a bug with a plugin
