### ISSUE TITLE
Templates from plugins are cached too eagerly

### ISSUE THREAD

**Issue by pereiss** [grails/grails-core#10339]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem attached
- [x] Full description of the issue provided (see below)

This may be somewhat related to [#10047](https://github.com/grails/grails-core/issues/10047):
Having two plugins that provide the same template (same name, same path). First called template is cached and it's not possible anymore to access the template from the second plugin.

<g:render template="theTemplate" plugin="pluginA" />
<g:render template="theTemplate" plugin="pluginB" />

### Expected Behaviour

Content of pluginA's template followed by content of pluginB's template

### Actual Behaviour

Twice pluginA's content.

I was able to track this down to org.grails.web.gsp.GroovyPagesTemplateRenderer, method 

> private Template findAndCacheTemplate(Object, TemplateVariableBinding, String, String, String, final String)

        scriptSource = groovyPageLocator.findTemplateInBinding(controller, pluginName, templatePath, pageScope);
       ...
        if (scriptSource == null) {
            cacheKey = contextPath + pluginName + uri;
        } else {
            cacheKey = scriptSource.getURI();
        }

 Actually, scriptSource is not null (since fix for [#10047](https://github.com/grails/grails-core/issues/10047)?) and going into the else-branch (omitting pluginName) is wrong.

### Steps to Reproduce/Example Application

1. git clone https://github.com/pereiss/templatebug.git
2. cd templatebug/myapp
3. grails run-app
5. call http://localhost:8080

### Environment Information

- **Operating System**: Ubuntu Linux 16.04
- **Grails Version:** 3.1.11+,  3.2+
- **JDK Version:** jdk8

[templatebug.zip](https://github.com/grails/grails-core/files/625778/templatebug.zip)

**Comment by graemerocher** [comment]
The attached zip seems to be corrupt, could you possibly upload again or provide a github repo for the example?

**Comment by pereiss** [comment]
Ok, I put it into a github repo: https://github.com/pereiss/templatebug

**Comment by graemerocher** [comment]
Thanks
