### ISSUE TITLE
Grails 3.2.7 - building war with custom env results in wrong env being set

### ISSUE THREAD

**Issue by ilPittiz** [grails/grails-core#10546]
Assembling a war archive with Grails 3.2.7 while setting a custom environment with `-Dgrails.env` parameter doesn't result in the specified environment being set.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present)
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download sample application from [Github](https://github.com/ilPittiz/grailsCustomEnv).
Note that in `application.groovy` there's the `a` property with different values for different environments, in order:
    - `development`
    - `staging`
    - `qa`
    - `production`
2. Build war (terminal)
`> grails -Dgrails.env=staging war`
I used the terminal, but also using Gradle tasks (my regular deployment flow) gives the same result.

### Expected Behaviour

Application being assembled with expected `staging` environment configuration.

### Actual Behaviour

This is the output from the terminal
```
| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

Total time: 0.961 secs
:compileJava NO-SOURCE
:compileGroovy
:findMainClass
:buildProperties
:processResources
:classes
:compileWebappGroovyPages NO-SOURCE
:compileGroovyPages
:war
:bootRepackage
:assemble

BUILD SUCCESSFUL

| Built application to build/libs using environment: development
```
Note the `development` environment being used.

Strangely enough, after unpacking the war file, this is instead what the `./WEB-INF/classes/META-INF/grails.build.info` file states:
```
info.app.version=0.1
info.app.name=env
grails.env=qa
info.app.grailsVersion=3.2.7
```
The `qa` env was set?

### Notes

A few thing I noted:
- on any previous Grails version (e.g. 3.2.6) this issue doesn't occur
- creating war archive specifying non-custom enviroments works fine (both the output from the terminal and `grails.build.info` files are consistent with the input)
- no issue occurring when running the app with any environment. There's a basic page on root path printing out the value of `a` property if you want to check this.
- I couldn't figure out the (wrong) logic used to get the env when building the war file, but I got the feeling it has something to do with the amount and order of the env-dependent specializations in `application.groovy`.
My example highlights the issue to the extremes.

### Environment Information

- **Operating System**: macOS 10.12.3
- **Grails Version:** 3.2.7
- **JDK Version:** 1.8.0_60

### Example Application

https://github.com/ilPittiz/grailsCustomEnv

**Comment by jameskleeh** [comment]
Using 3.2.8.BUILD-SNAPSHOT produces the correct environment name in `grails.build.info`. I was not able to reproduce the "qa" environment getting set there. For me it was "development". Even with 3.2.8 the message displayed ("Built application to...") is incorrect.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails-profiles/base/commit/1f1ea0989d6222f39a20322d5c6d15f037667abb
