### ISSUE TITLE
"No Session found for current thread" running an integration test using hibernateManagedSession=true

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-core#10570]
I'm upgrading an application from Grails 2.5.4 to Grails 3.2.8 which uses transactionManager.hibernateManagedSession = true. The application relies on PostgreSQL database session variables, and this was the method we found to ensure the session variables do not change across transactions in a single request.

The application runs fine with this setting, but integration tests fail with an error:
```
org.springframework.dao.DataAccessResourceFailureException: Could not obtain Hibernate-managed Session for Spring-managed transaction; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doGetTransaction(HibernateTransactionManager.java:393)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:337)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at grails.transaction.GrailsTransactionTemplate.executeAndRollback(GrailsTransactionTemplate.groovy:67)
	at test.hibernate.session.TestServiceSpecification.testHibernateSessionSettings(TestServiceSpecification.groovy)
Caused by: org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:116)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:688)
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doGetTransaction(HibernateTransactionManager.java:386)
	... 4 more
```

This happens whether I set hibernateManagedSession in BootStrap.init or application.yml (beans.transactionManager.hibernateManagedSession).

I'm attaching a simple application that reproduces the problem. Grails run-app shows that the TestController works fine. Running test-app -integration produces the error.

I don't understand the change in behavior between run-app and test-app. Is there something I'm missing in the integration test to be able to test-app with hibernateManagedSession?

### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded
- [x] Full description of the issue provided

### Environment Information
- **Operating System**: Windows 10
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_121

### Example Application
[test-hibernate-session.zip](https://github.com/grails/grails-core/files/903809/test-hibernate-session.zip)

**Comment by timbonicus** [comment]
In the run-app scenario, [HibernateTransactionManager#376](https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L376) returns a sessionHolder; in test-app it is null, and falls into the second block on #384 where the error occurs.

In run-app, TransactionSynchronizationManager.bindResource for SessionHolder is called by the OpenSessionInViewInterceptor, but nothing calls this when executing the test run. Should GrailsTransactionTemplate.executeAndRollback bind the SessionHolder?

**Comment by graemerocher** [comment]
it does when `transactionManager.hibernateManagedSession = false` but seemingly changing this setting prevents the binding from happening, hence the issue.

**Comment by graemerocher** [comment]
As you can see from this line:

https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L521

The transaction manager will bind a new session using `TransactionSynchronizationManager.bindResource`, but only if it is a newly created session. By setting `hibernateManagedSession` to `true` it ends up calling `txObject.setExistingSession(session);` which makes `txObject.isNewSessionHolder()` return `false.

The reason why it "works" in `run-app` is the presence of the `OpenSessionInViewInterceptor`, if you were to disable this interceptor it would also fail.

In fact it would fail anywhere this interceptor is not present. 

As per the javadoc of `setHibernateManagedSession`:

 https://github.com/spring-projects/spring-framework/blob/master/spring-orm/src/main/java/org/springframework/orm/hibernate5/HibernateTransactionManager.java#L261

If you set it to true you have to also supply a custom `org.hibernate.context.spi.CurrentSessionContext` that provides the ability to lookup the session when doing `sessionFactory.currentSession`.

Currently it is using `GrailsSessionContext` https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/GrailsSessionContext.java

But because you disable the binding of the session by setting `hibernateManagedSession` to `true` this results in `GrailsSessionContext` no longer working and hence your error.

As fas as I can see this is not a bug and everything is working as designed. If you want to set `hibernateManagedSession` to `true` then you must implement your own `CurrentSessionContext` and configure it by setting `hibernate.current_session_context_class` to the name of this class in your configuration.
