### ISSUE TITLE
Integration test regression involving new sessions between 3.1.x and 3.2.x

### ISSUE THREAD

**Issue by joemccall86** [grails/grails-core#10599]
Given a GORM object is persisted in a spec with `.save(flush: true, failOnError: true)`, when that same object is searched for in the database it is expected that the object is found. This behavior was true in 3.1.12, but appears to be broken in 3.2.8.

In short, given this test:

```
    void "test something"() {
        setup:
        new Person(name: "John Doe").save(failOnError: true, flush: true)

        when:
        def retrievedPerson
        Person.withNewSession {
            retrievedPerson = Person.findByName("John Doe")
        }

        then:
        retrievedPerson
    }
```

Grails 3.1.12: 
`retrievedPerson` is not null

Grails 3.2.8:
`retrievedPerson` is null

### Task List

- [x] Steps to reproduce provided
- [x] ~Stacktrace (if present) provided~ Not present
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Write an integration test that retrieves a persisted object in a new session
2. Run tests with `grails test-app -integration`
3. Observe the result

### Expected Behaviour

The object is retrieved from the new session for both Grails 3.1.12 and Grails 3.2.8.

### Actual Behaviour

The object is retrieved in Grails 3.1.12, but is null in Grails 3.2.8

### Environment Information

- **Operating System**: Ubuntu MATE 17.04
- **Grails Version:** 3.1.12, 3.2.8
- **JDK Version:** openjdk version "1.8.0_121"

### Example Application

Grails 3.1.12 example:
https://github.com/joemccall86/sessionproblem3112

Grails 3.2.8 example:
https://github.com/joemccall86/sessionproblem328

**Comment by jeffbrown** [comment]
I expect that the test at https://github.com/joemccall86/sessionproblem328/blob/a34142be61f4c54a9998b436559c42c03616291d/src/integration-test/groovy/sessionissue328/SomeSpec.groovy#L18-L30 will pass if you replace `withNewSession` with `withSession` or if you just removed the session explicit stuff altogether and just invoked the query.

Can you confirm that to be the case?

Thanks for the feedback.

**Comment by joemccall86** [comment]
I can confirm that in both of those cases the test passes. I'm still not sure why `withNewSession` would fail though.

**Comment by jeffbrown** [comment]
> I can confirm that in both of those cases the test passes.

Thanks for the feedback.

**Comment by graemerocher** [comment]
`withNewSession` opens a new connection, since the test runs within its own transaction the changes are not visible to `withNewSession`. This is the expected behaviour and in previous version it was a bug that `withNewSession` used the same connection.
