### ISSUE TITLE
Additional query parameters lost with UrlMappings redirect in Grails 3

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-core#10622]
I have a permanent redirect defined in UrlMappings. In Grails 2.5.4, any additional query parameters supplied to the old URL (e.g. ?xyz=123) were passed through to the redirect endpoint. In Grails 3.2.8, this behavior has changed; the additional query parameters are not passed along.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the attached Grails 3.2.8 application (test-redirect.zip)
2. Navigate to http://localhost:8080/test/deprecated?xyz=123
3. Note that the xyz parameter **is not** listed.
4. Run the attached Grails 2.5.4 application (test-redirect2.zip)
5. Navigate to http://localhost:8080/test-redirect2/test/deprecated?xyz=123
6. Note that the xyz parameter **is** listed.

### Expected Behaviour

The redirect location should include the xyz parameter.

### Actual Behaviour

The redirect location loses any additional query parameters.

### Environment Information

- **Operating System**:  Windows 10
- **Grails Version:** Grails 3.2.8
- **JDK Version:** 1.8.0_121

### Example Application
Grails 3.2.8:
[test-redirect.zip](https://github.com/grails/grails-core/files/974802/test-redirect.zip)

Grails 2.5.4:
[test-redirect2.zip](https://github.com/grails/grails-core/files/974803/test-redirect2.zip)

**Comment by timbonicus** [comment]
Both Grails versions also issue a 302 HTTP status code for the redirect, even though `permanent: true` is set in UrlMappings. Shouldn't this be a 301 (permanent) redirect?

**Comment by sdelamo** [comment]
You are not getting a 301 because you URLMapping is formatted incorrectly instead of: 

`        "/test/deprecated" (redirect: "/test/newHotness", permanent: true)`

it should be: 

`"/test/deprecated" (redirect: [uri: "/test/newHotness", permanent: true])
`

**Comment by sdelamo** [comment]
If you want to forward URL params into the redirected action. 

`http://localhost:8080/test/deprecated?xyz=123`

301 redirect to:

`http://localhost:8080/test/newHotness?xyz=123`

You could setup an action method such as: 

```
 def deprecated() {
        redirect action: 'newHotness', permanent: true, params: params
    }
```

**Comment by timbonicus** [comment]
Whoops, good catch on the UrlMappings formatting @sdelamo.

The params forwarding could work around the issue in this trivial case. We have UrlMappings for legacy Struts endpoints that I don't think map so nicely to Grails routing, such as:
```
name legacyPdfAction "/users/listAllUsers!prepareAsPdf.action" (redirect: [uri: "/users/list.pdf", permanent: true])
```
It's also unfortunate to need extra controller endpoints just to handle param forwarding. I thought this might be worth a look especially since it's a behavior change from Grails 2.

**Comment by owenrubel** [comment]
Well also, the HandlerInterceptor no longer handles the 'uri'. This was previously available and was removed in 3.1. You actually have to add in the 3.1 RequestForwarder if you want to be able to get it to work properly.

**Comment by owenrubel** [comment]
This should be handled with the 'forward' rather than a redirect so that it is CLEAR what the functionality is.

Using a redirect implies it is using the same request/response; if it is forwarding, it is NOT. This is poor functionality and should be more clear.

**Comment by owenrubel** [comment]
As **Spring (the makers of Spring Boot)** put it:
`"forward happens entirely on a server side..."`
Thus a URI, is most definitely a forward... **not a redirect.**

This is bad functionality.
