### ISSUE TITLE
Parameters resolved from URL are lost when an exception routes to an error controller

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-core#10623]
The attached example application has a TestController endpoint that intentionally throws an error to simulate an application problem. The ErrorController is mapped to 500 errors in UrlMappings, and contains a withFormat block to respond appropriately based on whether the request was made with JSON/AJAX or HTML.

The prints show that the format parameter is lost between the controllers, which causes the withFormat to always execute the `html` block. Results from the test/index page:

```groovy
// Clicked "Submit exception-throwing form" button
Format in TestController: null
Format in ErrorController: null

// Clicked "Submit exception-throwing JSON request" button
Format in TestController: json
Format in ErrorController: null
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the attached example application
2. Click each submit button to see the print-outs above
3. Open browser tools/Network tab to see HTML response to JSON request

### Expected Behaviour

The withFormat / json block in ErrorController should be executed for a JSON request.

### Actual Behaviour

The withFormat / html block in ErrorController is executed for both HTML and JSON requests.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.2.8
- **JDK Version:** 1.8.0_121

### Example Application
[error-controller.zip](https://github.com/grails/grails-core/files/974861/error-controller.zip)

**Comment by sdelamo** [comment]
You have work around.

You can execute: 

`localhost:8080/test/exceptionThrowingEndpoint?format=json`

instead of: 

`localhost:8080/test/exceptionThrowingEndpoint.json`

**Comment by timbonicus** [comment]
Thanks @sdelamo, this is a reasonable workaround for withFormat. I discovered that other URL-based parameters are lost also, such as params.id, which is harder to work around this way.

**Comment by sdelamo** [comment]
Do you mean id extracted from the uri, such as id = 1 from:

`/book/show/1`

**Comment by timbonicus** [comment]
@sdelamo Yes, we found params.id as in your example being lost too. I can work up an example if that would be helpful.

**Comment by sdelamo** [comment]
What it is that you are trying to achieve, in your error actions?

**Comment by timbonicus** [comment]
I should mention that we are upgrade an application from Grails 2.5.4 to Grails 3.2.8, so this seems to be a behavior change in Grails 3.

**Comment by timbonicus** [comment]
@sdelamo At a high level, displaying different concurrency errors based on what action the user was taking. The params can help resolve this at the ErrorController level.

We could instead throw different exceptions and handle this with different UrlMappings, but in a practical sense this gets difficult with service code that is shared across many types.

**Comment by timbonicus** [comment]
@sdelamo @graemerocher Any feedback on why this issue was closed? As mentioned above, the workaround is not great.

**Comment by sdelamo** [comment]
@timbonicus  It was closed because the pull request https://github.com/grails/grails-core/pull/10631/ referenced int the issue's comments fixes the reported problem. 

You can verify the fix by upgrading the attached sample app 3.2.8 to Grails 3.2.10. 

https://github.com/erichelgeson/grails-versions/compare/3.2.8...3.2.10

By updating the Grails and Gorm Version in gradle.properties. 

grailsVersion=3.2.10
gormVersion=6.0.10.RELEASE
gradleWrapperVersion=3.4.1

**Comment by timbonicus** [comment]
@sdelamo Thanks, I overlooked the pull request. I appreciate the pointer, I'll try out an upgrade to 3.2.10.

**Comment by timbonicus** [comment]
I upgraded to 3.2.10 and the problem still remains for my project. It appears that [GrailsExceptionResolver#164](https://github.com/grails/grails-core/blob/master/grails-web-mvc/src/main/groovy/org/grails/web/errors/GrailsExceptionResolver.java#L164) does not return a match.

If I run the same urlMappings.match against the requestURI *with the server.contextPath removed*, I do get a requestInfo result. Should this code be handling contextPath?
