### ISSUE TITLE
Executing Grails 3 application using the main method in the Application class causes a MissingMethodException

### ISSUE THREAD

**Issue by sosguthorpe** [grails/grails-core#10676]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example Project
- [x] Full description of the issue provided (see below)

### Example Project in Git
https://github.com/sosguthorpe/grails-issue-10676

### Steps to Reproduce

1. Create Grails application using the restl-api profile
`grails create-app --profile=rest-api testing` 

2. Create a domain class.
`grails create-domain-class Book`

3. Execute in IDE (Eclipse Neon.3) using Application.groovy

### Expected Behaviour

Application starts normally.

### Actual Behaviour

Application fails on startup with stacktrace:

```
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@bf1ec20: startup date [Wed Jun 14 14:20:25 BST 2017]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968) [spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555) [spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) [spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:83) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:388) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:375) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-3.2.10.jar:3.2.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.10.jar:2.4.10]
	at testing.Application.main(Application.groovy:8) [bin/:na]

2017-06-14 14:20:26.363 ERROR 19290 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor' defined in testing.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) ~[spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-1.4.6.RELEASE.jar:1.4.6.RELEASE]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:83) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:388) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp.run(GrailsApp.groovy:375) [grails-core-3.2.10.jar:3.2.10]
	at grails.boot.GrailsApp$run.call(Unknown Source) [grails-core-3.2.10.jar:3.2.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) [groovy-2.4.10.jar:2.4.10]
	at testing.Application.main(Application.groovy:8) [bin/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 23 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-2.4.10.jar:2.4.10]
	at org.grails.core.util.ClassPropertyFetcher$GetterPropertyFetcher.get(ClassPropertyFetcher.java:311) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.util.ClassPropertyFetcher.getPropertyWithFetcherAndCallback(ClassPropertyFetcher.java:235) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.util.ClassPropertyFetcher.getPropertyValueWithFetcher(ClassPropertyFetcher.java:229) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.util.ClassPropertyFetcher.getPropertyValue(ClassPropertyFetcher.java:224) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.DefaultGrailsDomainClassProperty.getTransients(DefaultGrailsDomainClassProperty.java:174) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.DefaultGrailsDomainClassProperty.<init>(DefaultGrailsDomainClassProperty.java:108) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.DefaultGrailsDomainClass.populateDomainClassProperties(DefaultGrailsDomainClass.java:199) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.DefaultGrailsDomainClass.<init>(DefaultGrailsDomainClass.java:113) ~[grails-core-3.2.10.jar:3.2.10]
	at org.grails.core.artefact.DomainClassArtefactHandler.newArtefactClass(DomainClassArtefactHandler.java:76) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:794) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:490) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:761) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplicationPostProcessor.groovy:112) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPostProcessor.groovy:93) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.boot.config.GrailsApplicationPostProcessor.setApplicationContext(GrailsApplicationPostProcessor.groovy:225) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:77) ~[grails-core-3.2.10.jar:3.2.10]
	at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.groovy:68) ~[grails-core-3.2.10.jar:3.2.10]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 24 common frames omitted
Caused by: groovy.lang.MissingMethodException: No signature of method: static org.grails.datastore.mapping.dirty.checking.DirtyCheckable.$static$init$org_grails_datastore_mapping_dirty_checking_DirtyCheckable__DIRTY_CLASS_MARKER() is applicable for argument types: (java.lang.Class) values: [class testing.Book]
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1506) ~[groovy-2.4.10.jar:2.4.10]
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1492) ~[groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:899) ~[groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168) ~[groovy-2.4.10.jar:2.4.10]
	at org.grails.datastore.mapping.dirty.checking.DirtyCheckable$Trait$Helper.$static_methodMissing(DirtyCheckable.groovy) ~[grails-datastore-core-6.0.10.RELEASE.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-2.4.10.jar:2.4.10]
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1504) ~[groovy-2.4.10.jar:2.4.10]
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1492) ~[groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:65) ~[groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194) [groovy-2.4.10.jar:2.4.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206) [groovy-2.4.10.jar:2.4.10]
	at testing.Book.<clinit>(Book.groovy) ~[bin/:na]
	... 51 common frames omitted
```

### Environment Information

OS: Ubuntu 16.04
Eclipse: Neon.3
Grails Version: 3.2.10
Groovy Version: 2.4.10
JVM Version: 1.8.0_131

**Comment by jameskleeh** [comment]
I can't reproduce. Please upload an example project.

**Comment by sosguthorpe** [comment]
I have updated the original issue with a git url.

**Comment by sosguthorpe** [comment]
It is worth noting that the application runs fine using
`grails run-app`
or
`gradle bootRun`

Also that the app will start from the IDE if I remove the domain class.

**Comment by graemerocher** [comment]
Can't reproduce this with the referenced example personally

**Comment by skufle** [comment]
I upgraded my relatively small application from Grails 3.2.10 to 3.2.11 by changing grailsVersion in my gradle.properties file and it fails in exactly the same manner but both when started via gradlew and grailsw.

Downgrading my application to 3.2.10 again fixed it.

**Comment by graemerocher** [comment]
The root cause of this issue is that you are running with a version of Groovy older than 2.4.11

Verify you have no versions of `groovy-all` on your classpath that are in conflict.

**Comment by skufle** [comment]
Upgrading gormVersion to 6.0.12.RELEASE seems to have fixed my problem.

**Comment by sosguthorpe** [comment]
@skufle Thanks for that. I can confirm also that it was an older version of Gorm adding groovy 2.4.10 to my classpath. Thanks to you and @graemerocher.

Closing now as this is resolved.
