### ISSUE TITLE
grails create-service applies the deprecated annotation @Transactional

### ISSUE THREAD

**Issue by rmorrise** [grails/grails-core#10682]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- N/A Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new grails app (here I used --profile=angular)
2. Create a service "Bar" using the CLI

D:\temp>grails --version
| Grails Version: 3.3.0.M2
| Groovy Version: 2.4.11
| JVM Version: 1.8.0_66
D:\temp>grails create-app foo --profile=angular
| Application created at D:\temp\foo
|
This profile has created a multi-project build where the "server" module contains the Grails application and the "client" module contains the Angular 2 applica
ion.

To start the Grails application separately, execute "./gradlew server:bootRun"
To start the client side application separately, execute "./gradlew client:bootRun"

To start both the client and server applications simultaneously, execute "./gradlew bootRun --parallel"

D:\temp>cd foo/server

| Resolving Dependencies. Please wait...

CONFIGURE SUCCESSFUL

Total time: 7.814 secs
| Created grails-app/services/foo/BarService.groovy
| Created src/test/groovy/foo/BarServiceSpec.groovy
D:\temp\foo\server>cd grails-app/services/foo

D:\temp\foo\server\grails-app\services\foo>type BarService.groovy
package foo

import grails.transaction.Transactional

@Transactional
class BarService {

    def serviceMethod() {

    }
}

### Expected Behaviour

The created service should not contain deprecated code.

### Actual Behaviour

The new service is marked with the _grails.transaction.Transactional_ annotation, which is deprecated.

### Environment Information

- **Operating System**: Win7 x64
- **Grails Version:** 3.3.0.M2
- **JDK Version:** 1.8.0_66
- **Container Version (If Applicable):** N/A
