### ISSUE TITLE
Deployed grails application periodically loses context root

### ISSUE THREAD

**Issue by Trebla7th** [grails/grails-core#10798]
First, I apologize if this is the wrong place to post, I've posted the issue on StackOverflow with bounties and nobody has been able to posit any solutions, something is obviously not behaving correctly, and it appears to be something within grails.  I understand if you just close this as it has been exceptionally difficult to reproduce reliably and I cannot upload the source code.  Hopefully it will at least linger in someone's subconscious in case someone dreams about it.  We are completely at a loss and have not found any indication of why this happens.

## Bug Description

We have roughly a dozen applications deploying to the same tomcat server and two of the applications will occasionally lose their relative context root path.  

Let's say we have "app1" and "app2" which deploy to server:port/app1 and server:port/app2.

app1 works just fine, but app2 will SOMETIMES deploy and all <g:link/> links (or any other grails generated URLs, such as asset locations) generate relative to the server root instead of the application root... the application is correctly deployed under /app2, so the links point to bad locations.

E.g., <g:link controller='hello' action='index'/> will generate the link as "/hello/index" rather than "/app2/hello/index".  This is true for all links, including asset locations.

It appears to happen at some point after startup, the applications will start fine, and work for a day or so, then the bug will surface, the only fix appears to be to restart tomcat.

This was an issue in grails 2.5.1 and continues in grails 3.2.10, but anecdotally appears to be getting more frequent.

We have ~20 production servers in "identical" configurations, and this is only happening on two servers.  We cannot reproduce it on any other servers.  It is always the same 2 applications on the same 2 servers that experience the issue.  There are no significant differences in any application in the build.gradle (identical plugins in some cases, repos, etc) or settings.gradle (only difference is the rootProject.name).  The gradle.properties file is identical in most applications.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see above)

### Steps to Reproduce

1. Cannot reliably reproduce

### Expected Behaviour

URLs generated by grails should properly prepend the application's context path to the front of each link.

### Actual Behaviour

All URLs generated by grails lack the context path and cause the application to be non-functional in certain situations.

### Environment Information

- **Operating System**: RHEL 6
- **Grails Version:** 3.2.10 (same issue on 3.2.8 and 2.5.1)
- **JDK Version:** 
java version "1.7.0_151"
Java(TM) SE Runtime Environment (build 1.7.0_151-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.151-b15, mixed mode)
- **Container Version (If Applicable):** apache tomcat 7.0.57

### Example Application

- I apologize, I cannot upload our production applications and we have not been able to reproduce this with sample applications.

**Comment by hbogaards** [comment]
We are encountering this same issue with only 1 of our Grails applications (using Grails 3.2.7 and asset plugin version 2.13.1).
And mostly on only 1 of our environments (sadly on our production environment...)

@Trebla7th Can you link the Stackoverflow question?

We are running on Tomcat 8.0.32 with Java 1.8.0_151 on RHEL 6

**Comment by Trebla7th** [comment]
Sad to see this closed without comment or resolution, we still experience this issue regularly.

**Comment by ilopmar** [comment]
Have you tried to upgrade to the latest Grails 3.3.6 version? I'm sorry but it's almost impossible to fix this without a sample application to be able to reproduce the issue.

**Comment by Trebla7th** [comment]
I understand, but even were I able to attach our applications, the issue is sporadic and only occurs on a few (I think we've seen it on 4 servers) of our ~15 deployments, the vast majority of which are "identical" (at least in terms of configuration).  We are currently on grails 3.3.2 and still see the issue regularly.

Anecdotally, it appears to happen most frequently (possibly exclusively, but it's rare enough that we don't have good data) after installing a new version of the affected applications.  Several developers have spent significant time investigating possible causes with no progress.  Our "resolution" was to add monitoring that explicitly checks for missing context root and restarts the server when detected.

**Comment by ilopmar** [comment]
Thanks. I also understand that this can be frustrating some times.

**Comment by Trebla7th** [comment]
We finally discovered the cause of this.  `grailsLinkGenerator` (`DefaultLinkGenerator` class) is either losing `contextPath` or it is not getting set correctly on startup.  This causes all links generated using the link generator singleton (which is most, but apparently not all) to generate at server root.

We're still working on timing to figure out if this can be run in `BootStrap` and deferred until the server startup is complete, but for now, as a workaround, we've added an unprotected controller action to reset this, which appears to resolve the issue (until the next time the server is restarted).

```
def resetContextPath() {
  grailsLinkGenerator.contextPath = grailsApplication.config.getProperty("server.contextPath")
}
```

**Comment by Trebla7th** [comment]
We still can't reliably reproduce it either...  just have to try a fix and wait til it occurs again.  Also found that we need:

```
    if (grailsLinkGenerator instanceof CachingLinkGenerator) {
      grailsLinkGenerator.clearCache()
    }
```

Still only on SOME servers in SOME apps SOME of the time.

**Comment by bobbywarner** [comment]
Closing as issue reporter can't reproduce the issue.

Please open a new issue if/when the issue can be reproduced.

**Comment by alphaadidas** [comment]
happens to me too.  adding the hack mentioned above.
