### ISSUE TITLE
Grails 3.3.2 doesn't work with java 7.  Error initializing classpath: com/energizedwork/gradle/webdriver/WebDriverBinariesPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tircnf** [grails/grails-core#10884]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Have java 1.7 installed.
2. export JAVA_HOME = java 1.7 install dir.
3. install grails 3.3.2 (sdk use grails 3.3.2)
4.  grails create-app app332
5.  cd app332
6. run the grails command.

### Expected Behaviour
You should get a grails command prompt.

### Actual Behaviour
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\workspaces\new_grails\patient332\build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'patient332'.
> java.lang.UnsupportedClassVersionError: com/energizedwork/gradle/webdriver/WebDriverBinariesPlugin : Unsupported major.minor version 52.0

### Environment Information

- **Operating System**: windows
- **Grails Version:** 3.3.2
- **JDK Version:** 1.7.0_X
- **Container Version (If Applicable):** NA

### Example Application

NA.  The default application built with "create-app" does it.  It appears to be an issue with the WebDriverBinariesPlugin.

This issue does not exist in grails 3.2.9

**Comment by sdelamo** [comment]
Grails 3.3 will have two features 

- `geb`     (JDK7 compatible) adds Geb 1.1.1 and WebDriver 2.47.1
- `geb2`  (JDK8 compatible) adds Geb 2 and WebDriver 3.x

If you are using JDK7 with Grails 3.3.2 please configure Geb 1.1.1 as shown in the next repository:

https://github.com/grails-samples/geb-example-grails/tree/geb-1.1.1
