### ISSUE TITLE
Grails 3.3.2: LazyInitializationException raised in views trying accessing records in related domains 

### ISSUE THREAD

**Issue by leleFc** [grails/grails-core#10899]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Grails 3.3.2 app 
2. Configure multiple datasources (at least 1, plus the default "datasource")
3. Create 2 domains (one as "father", one as "child" with "belongsTo" and "hasMany" relations) and map them to "ALL" datasources (see provided example)
4. Create controller and views using scaffolding
5. Fill "father/child" domains with some records using a specific datasource different from the default
6. Adapt code in controller to specify which datasurce the domains must use
7. Run the app and try to list the father records using the auto-generated views

### Expected Behaviour

The "father/child"records are displayed without problems

### Actual Behaviour

A "LazyInitializationException" is raised and it isn't possible to display records.
This not happens using Grails 3.1.16 (I'm upgrading an application created with Grails 3.1.16 to Grails 3.3.2) with multiple datasources, or using Grails 3.3.2 but with domains configured on a single datasource

[stacktrace.txt](https://github.com/grails/grails-core/files/1614809/stacktrace.txt)

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.2
- **JDK Version:** 1.8.0 update 131
- **Container Version (If Applicable):** Embedded Tomcat

### Example Application

https://github.com/leleFc/app_332.git

**Comment by graemerocher** [comment]
See http://docs.grails.org/latest/guide/upgrading.html

Section "TransactionManager Chaining for Multiple Data Sources Disabled by Default"

**Comment by leleFc** [comment]
Hi @graemerocher, I forgot to specify that the "TransactionManager Chaining" was enabled inside "application.yml".
The exeption occours into the view, inside the gsp code, not inside the controller or service code.

**Comment by leleFc** [comment]
Solved by adding "hibernate.enable_lazy_load_no_trans: true" in "application.yml"
