### ISSUE TITLE
loadAfter for plugin only works property with ./gradlew bootRun and not grails run-app

### ISSUE THREAD

**Issue by rvanderwerf** [grails/grails-core#11004]
### Task List

Steps to reproduce provided
- [ ] Override a spring security auth page on a plugin 
- [ ] add loadAfter = ['springSecurityCore']
run security-app via ./gradlew bootRun
You can see the overridden auth.gsp
stop app
run app with 'grails run-app' via 3.3.1
hit index page - instead you now see auth.gsp from inside spring security core.

- [ ] Example that reproduces the problem uploaded to Github - see attached

### Expected Behaviour

When running grails run-app it should preserve application plugin load order and response loadsAfter from the plugin overriding another.

### Actual Behaviour
works with ./gradlew bootRun
does not work with grails run-app

Tell us what happens instead

### Environment Information

- **Operating System**: Linux
- **Grails Version:** 3.3.1
- **JDK Version:** JDK 8, happens on all current versions
- **Container Version (If Applicable):** none

[grails_render_issue_workaround.zip](https://github.com/grails/grails-core/files/1981361/grails_render_issue_workaround.zip)

This is an OCI Customer ticket submitted issue.

**Comment by benrhine** [comment]
`loadAfter` seems to be functioning correctly. After many runs with both logging and debugging at no point was userCore ever observed to load before springSecurity running with either grails or gradle.

**Comment by puneetbehl** [comment]
@rvanderwerf  It seems like this is working after I add the dependency as following:
```
grails {
    plugins {
        compile project(':user-core')
    }
}
```

**Comment by benrhine** [comment]
As an additional aside while looking into another issue last week I had to read through the [plugin documentation](http://docs.grails.org/latest/guide/plugins.html) (look under - Providing Views, Templates and View resolution) and it specifically states that you can override a plugin view with a view in the app itself but does not discuss if it is possible to override a view in one plugin with the view in another. So perhaps something to consider that it may not be fully supported in that manner.
