### ISSUE TITLE
Gradle 5 - Grails 3 simple multi-project app/plugin won't compile

### ISSUE THREAD

**Issue by nutmix** [grails/grails-core#11221]
## Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github - [[ non needed]]
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a new plugin:
     $ grails create-plugin core --profile=plugin --features=hibernate5,events
2. create a new app to use that plugin]
    $ grails create-app myapp
3. create settings.gradle at the same dir as core/myapp:
    include "myapp","core"
4. add the dependency to  myapp build.gradle:
```
grails {
    plugins {
        compile project(':core')
    }
}
```

4. try to compile either the plugin, or the application (both give identical results) . THis fails with error below, as do commands to create new domain objects etc.

### Expected Behaviour

App or plugin compiles

### Actual Behaviour

```
| Resolving Dependencies. Please wait...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/me/dev/grails_projects/tst/core/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':core'.
> Failed to apply plugin [id 'org.grails.grails-plugin']
   > Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```
### Environment Information

- **Operating System**: OSX10.13.6
- **Grails Version:** 3.3.9
- **JDK Version:** 1.8.0_131
- **Container Version (If Applicable): NA

### Example Application

There is no source code to upload, as commands to create new domain objects etc. also fail with the same error.

Here is the build.gradle from the core plugin. Note, line 17 is:
`apply plugin:"org.grails.grails-plugin"`

```
buildscript {
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
        classpath "org.grails.plugins:hibernate5:${gormVersion-".RELEASE"}"
    }
}

version "0.1"
group "core"

apply plugin:"eclipse"
apply plugin:"idea"
apply plugin:"org.grails.grails-plugin"
apply plugin:"org.grails.grails-plugin-publish"

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
}

dependencies {
    compile "org.springframework.boot:spring-boot-starter-logging"
    compile "org.springframework.boot:spring-boot-autoconfigure"
    compile "org.grails:grails-core"
    compile "org.grails.plugins:events"
    compile "org.grails.plugins:hibernate5"
    compile "org.hibernate:hibernate-core:5.1.16.Final"
    console "org.grails:grails-console"
    profile "org.grails.profiles:plugin"
    provided "org.grails:grails-plugin-services"
    provided "org.grails:grails-plugin-domain-class"
    runtime "org.glassfish.web:el-impl:2.1.2-b03"
    runtime "com.h2database:h2"
    runtime "org.apache.tomcat:tomcat-jdbc"
    testCompile "org.grails:grails-gorm-testing-support"
    testCompile "org.grails:grails-plugin-testing"
}

bootRun {
    jvmArgs('-Dspring.output.ansi.enabled=always')
    addResources = true
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}
// enable if you wish to package this plugin as a standalone application
bootRepackage.enabled = false
grailsPublish {
    // TODO: Provide values here
    user = 'user'
    key = 'key'
    githubSlug = 'foo/bar'
    license {
        name = 'Apache-2.0'
    }
    title = "My Plugin"
    desc = "Full plugin description"
    developers = [johndoe:"John Doe"]
}

```

Here is the full stack trace:

```
| Error Error initializing classpath: Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:89)
	at org.grails.gradle.plugin.core.GrailsGradlePlugin$_enableFileWatch_closure17.doCall(GrailsGradlePlugin.groovy:490)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.api.internal.project.DefaultProject.dependencies(DefaultProject.java:940)
	at org.gradle.api.Project$dependencies$1.call(Unknown Source)
	at org.grails.gradle.plugin.core.GrailsGradlePlugin.enableFileWatch(GrailsGradlePlugin.groovy:488)
	at org.grails.gradle.plugin.core.GrailsGradlePlugin.configureFileWatch(GrailsGradlePlugin.groovy:305)
	at org.grails.gradle.plugin.core.GrailsGradlePlugin.apply(GrailsGradlePlugin.groovy:118)
	at org.grails.gradle.plugin.core.GrailsPluginGradlePlugin.apply(GrailsPluginGradlePlugin.groovy:57)
	at org.grails.gradle.plugin.core.GrailsPluginGradlePlugin.apply(GrailsPluginGradlePlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:44)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_cld27zdkokaepye6lpqgvr80t.run(/Users/simonh/dev/grails_projects/tst3/common/build.gradle:17)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:177)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:182)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:573)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:125)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.getBuildAnalysis(DefaultGradleLauncher.java:88)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.configure(InProcessBuildActionExecuter.java:102)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:45)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:82)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:49)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:240)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
| Error Error initializing classpath: Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.


```

**Comment by nutmix** [comment]
Also tried with "corex" instead of core as the plugin name just in case core was reserved. Got same error.

**Comment by nutmix** [comment]
I just tried another experiement: if I crreate a plugin, it compiles. If I create an app, it compiles, but as soon as I add the settings.gradle file with include "myapp","myplugin", suddenly I cant compile anything.

**Comment by nutmix** [comment]
I also tried the following variants of settings.gradle:

1. include 'myapp', 'core'
2. include 'core', 'myapp'
3. include ":myapp", ":core"

All give the same error when trying to compile the plugin. If I remove the settings.gradle, the plugin will compile at least.

**Comment by norricorp** [comment]
I have the same problem.
~/grails/myApp $ grails -version
| Grails Version: 3.3.9
| JVM Version: 1.8.0_191
I run grails create-app myApp --profile=vue
~/grails/myApp $ ./gradlew server:bootRun
* Where:
Build file '/home/user/grails/myApp/server/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':server'.
> Failed to apply plugin [id 'org.grails.grails-web']
   > Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by dmatriccino** [comment]
After experiencing the same issue, I did some experimenting with different gradle versions. My first encounter, I was using gradle 5.1.1. Digging in gradle wrapper folder of a grails app, I noticed it uses gradle version 1.3.5. After downgrading to 1.3.5 (using sdkman), the multproject build worked. I continued to figure out the latest gradle version that works, and it looks like the latest version is 4.10.3 (5.0 showed the same error). You can probably move the wrapper folder that's included in a gradle app to the root folder of your grails multi project as well.

**Comment by jameskleeh** [comment]
Grails 3 currently does not explicitly support Gradle 5

**Comment by graemerocher** [comment]
Grails 4 will add support for Gradle 5, until then use the version Grails 3.x supports

**Comment by jhron** [comment]
I just found this issue because I have same problem using Grails 3.3.9, but using internal Grails Gradle 3.5 The symptoms are the same. I can not compile multi-project Grails application using simple example from Grails docs :(

**Comment by graemerocher** [comment]
Provide an example that reproduces the issue

**Comment by jhron** [comment]
Ok, I created repo here with freshly created example from Grails docs.
[https://github.com/jhron/grails-multiproject-test](url)

I have included output of grails run-app command too.

**Comment by nutmix** [comment]
Why has this been labeled wont fix? Its a pretty critical bug that with grails 3.3.9 grails is fundamentally broken and cant support mulit-module apps?  Does this mean the problem will never be fixed, and we have to go back to single monolithic grails apps or another framework?  I know many users who are still using grails 2.5 because grails 3 broke so much stuff, and 2.5 has far less bugs.  3 doesnt add any features worth upgrading from 2.5 to 3 for most people who just want to product apps with no fuss.  I can imagine that grails 4 will be the same way. I strongly beg someone to fix grails 3, as I wont be upgrading any time soon.

**Comment by jeffbrown** [comment]
> Its a pretty critical bug that with grails 3.3.9 grails is fundamentally broken and cant support mulit-module apps?

It is not the case that Grails 3.3.9 can't support multi-module apps.  It does support them.

**Comment by dmatriccino** [comment]
@nutmix - What version of gradle are you running? If you're running 5+, you will see this error and Grails 3 doesn't support Gradle 5, nor are they planning to. If using SDKMAN, you can switch to a lower version of Gradle and try building the multi-project again.

**Comment by jeffbrown** [comment]
> If you're running 5+, you will see this error and Grails 3 doesn't support Gradle 5, nor are they planning to.

Agreed.  I was addressing the claim "grails 3.3.9 grails is fundamentally broken and cant support mulit-module apps" which is not true.

**Comment by jeffbrown** [comment]
The project at https://github.com/jeffbrown/issue11221 contains a Grails 3.3.9 app which is a multi module build.  

    git clone git@github.com:jeffbrown/issue11221.git
    cd issue11221/
    ./gradlew app:bootRun

You will see that the app successfully includes the `DemoController` provided by the `helper` sub-module.

**Comment by jhron** [comment]
> The project at https://github.com/jeffbrown/issue11221 contains a Grails 3.3.9 app which is a multi module build.
> 
> ```
> git clone git@github.com:jeffbrown/issue11221.git
> cd issue11221/
> ./gradlew app:bootRun
> ```
> You will see that the app successfully includes the `DemoController` provided by the `helper` sub-module.

Yes, your example works. Your example in additional to my example contains in main directory "gradle" directory with Gradle wrapper.
Is it mandatory approach how to use multiproject project? If yes then it makes things clear.
When I installed Gradle 4 and set GRAILS_GRADLE_HOME variable to this Gradle 4 installation folder, or when I copy gradle folder from myapp folder to parent folder, then my example started to work too.

However when I delete this gradle folder from issue11221 parent folder and try inside app execute "grails run-app" , then it failed too with error:
`Build file 'C:\Temp\issue11221\app\build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'org.grails.grails-web']
   > Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

gradlew bootRun inside app folder still works without any problem even without "gradle" folder in parent folder.

**Comment by nutmix** [comment]
just to be clear, if you simply install grails 3.3.9, then follow my steps to reproduce, it will fail.  I think what people are saying is it is possible to modify 3.3.9 to get it to work with mulit-module projects, by downgrading certain components which are installed with 3.3.9 etc.  This is great, but then this must be included in big letters in the documentation, otherwise its a bug.

Don't get me wrong, I love grails, but it is far from the "works out of the box" it used to be with grails 2.5.  I wasted many days trying to get 3.3.9 working with multi-module projects, which have until now worked out of the box. many days = hundreds of dollars.  In the end I tried 3.3.8 in desperation and found it worked. If I had not found this, I would have gone back to 2.5.    I wasted even more weeks trying to get java.time.LocalDate or java.sql.Date to work (apparently its a data binding issue and is going to be fixed in version 4, which is of no use as we may never upgrade to that given that version 3 was missing critical features for nearly a year).  

Its things like this which I believe will stop adoption by the very developers grails is intended for: those looking to develop business functionally quickly without having to know/learn the complexity of the underlying technologies (such as spring, hibernate, gradle etc)

Personally, I would beg the gracious developers who maintain grails to not add any new versions until the issues with the current versions are fixed, and to make sure that future versions are as backwardly compatible as possible, i.e. offer an easy upgrade path.  If not, i believe grails will die.  All my colleagues who use grails stick with 2.5, as they view this as the last viable version for quick and painless application development.  Having spent tile with griails 3, I would agree. I have spent 30% of my time coding, and 70% finding work arounds for bugs/broken features.  This now makes me less productive than using plain J2EE + spring.

FYI, I know zero about gradle, as I come from a Maven/Ant background. I would argue that I should not have to know about it to use grails, I should just be able to download a version of grails (e.g. 3.3.9) and expect it to work, or, if there is a bug, it to be fixed in 3.3.10, not 4.0, which is likely to be far less stable and presumably not suitable for enterprise production development for some time.

**Comment by jeffbrown** [comment]
> Your example in additional to my example contains in main directory "gradle" directory with Gradle wrapper. Is it mandatory approach how to use multiproject project?

No, it isn't mandatory.  The whole thing can be done with out the `gradle` directory.  The `gradle` directory is there to support the bundled Gradle wrapper (`gradlew`) which has a number of benefits, but isn't required.

**Comment by jeffbrown** [comment]
> Sorry about the rant.

Right.  Much of the long post doesn't contribute directly to clarifying anything about the initial bug report.  Some of that would be better suited for a blog or maybe a personal diary.

Thanks for the feedback!

**Comment by jeffbrown** [comment]
As far as I can tell, the issue reported here is related to trying to use Gradle 5 with Grails 3.3.x, which isn't supported.

**Comment by codeconsole** [comment]
I don't think this error has to do with multi project apps.  I am having the same issue with a pretty basic app that I created and just tried migrating from 3.3.8 to 3.3.9.  I have no idea what is causing it.  Running any version other than 3.3.9 works fine. 

3.3.5 - app runs fine
3.3.6 - app runs fine
3.3.7 - app runs fine
3.3.8 - app runs fine
3.3.9 - Error initializing classpath: Could not find method runtimeOnly() for arguments 


```
$ grails -v
| Grails Version: 3.3.9
| JVM Version: 1.8.0_181

$grails run-app
| Resolving Dependencies. Please wait...

FAILURE: Build failed with an exception.

* Where:
Build file '/mydir/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'pixoto-new'.
> Failed to apply plugin [id 'org.grails.grails-web']
   > Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@6c60bf64.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.082 secs
| Error Error initializing classpath: Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher] on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@6c60bf64. (Use --stacktrace to see the full trace)
```

-----------------
Also, I have completely uninstalled gradle:

$ gradle
-bash: /Users/user/.sdkman/candidates/gradle/current/bin/gradle: No such file or directory

**Comment by codeconsole** [comment]
I am running the latest OSX with grails installed via sdkman

**Comment by jameskleeh** [comment]
@codeconsole Does `./gradlew bootRun` work? If so, then the version of Gradle being used is incorrect.

**Comment by codeconsole** [comment]
@jameskleeh yes, that works.  How is it using a wrong version of gradle?

**Comment by jameskleeh** [comment]
@codeconsole This is the logic that determines which gradle executable to use https://github.com/grails/grails-core/blob/3.3.x/grails-shell/src/main/groovy/org/grails/cli/gradle/GradleUtil.groovy#L50. Perhaps you have a `GRAILS_GRADLE_HOME` set? Or perhaps `gradleWrapperVersion` is not set correctly in the projects `gradle.properties`

**Comment by codeconsole** [comment]
@jameskleeh It's something specific about the project that is being upgraded because if I create a new project 
`grails create-app website` it works

`GRAILS_GRADLE_HOME` is not set

`gradleWrapperVersion=3.5` is set in gradle.properties which is identical to the value if I create new 3.3.9 project.

I guess the mystery is why does the identical code work with grails 3.3.8 and not 3.3.9 if the only change is  `grailsVersion=3.3.8` to `grailsVersion=3.3.9` in gradle.properties

Is there anything cached anywhere that can be causing an issue that maybe I need to delete?

**Comment by jameskleeh** [comment]
@codeconsole Impossible to say without a project to debug, but definitely seems like something specific to your app

**Comment by codeconsole** [comment]
I guess I will just create a new app from scratch and brute force the issue by moving every over piece by piece.

**Comment by codeconsole** [comment]
@jameskleeh 

ok, I have somewhat isolated the issue, but I still do not know what the root cause is.   It has to do with the location of the folder.

```
/workspace/app/
/workspace/app/newapp

```
The following DOES NOT work
```
cd /workspace/app/newapp
grails run-app
```

The following DOES WORK
```
mv /workspace/app/newapp /workspace
cd /workspace/newapp
grails run-app
```
 
This is only an issue with grails 3.3.9

Any ideas?

**Comment by codeconsole** [comment]
Ok, I have discovered the root cause.    The /app folder contains a file `settings.gradle` 
If I remove that file, it starts fine.

The /app folder really has nothing to do with /newapp.

If I place /newapp in another embedded subfolder I get the same issue
e.g. /app/example/newapp - Same error running from here.

So somehow `grails runapp` is effected by settings.gradle existing in a parent folder.

Again, any other version other than grails 3.3.9 will run without issue.

Any explanation for this?

**Comment by robertloeberdevelopment** [comment]
I'm new to grails, trying to rebuild a multi project from an old grails version. I ran into the same error building with inline plugins. 
Finally I found this tutorial:

https://guides.grails.org/grails-multi-project-build/guide/index.html

Now my plugin builds with the app.
The trick is that all the gradle files must be moved up from the app folder to the main folder of the multiproject.

**Comment by MichaelMorett** [comment]
FWIW, I just got the same error by attempting to upgrade to latest version of Geb (at time of writing):

testCompile "org.grails.plugins:geb:2.3.1"

If I switch back to testCompile "org.grails.plugins:geb:1.1.3", it doesn't exhibit the "Could not find method runtimeOnly() for arguments [io.methvin:directory-watcher]" error I am seeing.

**Comment by painfulcranium** [comment]
So I was just playing around with 3.3.9 as well with an example multi project app and ran into this. Seems if I copy the gradle directory from one of the projects to the top level folder that contains all the projects, it works as expected. Full disclosure, I have not tried this in 3.3.8 as others have stated and have said it works with that version. Just my two cents to the puzzle ;)

**Comment by pmcneil** [comment]
@robbugh and @codeconsole I suspect you have changed/upgraded just the grailsVersion in one of the projects - all the projects need to be the same version.
I saw the same problem in the shiro plugin, if you upgrade just one project you get this problem, upgrade them all.
So in gradle.properties for each project make sure you have the same grailsVersion. Hope that helps.

**Comment by dustindclark** [comment]
Holding all other things constant, this just happened to me while upgrading a Grails plugin from 3.3.2 to 3.3.10.  I ran `./gradlew build` on each Grails version in between, and it appears to have started with 3.3.9.  This is *not* a multi-project setup in my case...I'm simply trying to build a standalone Grails 3.3.10 plugin using gradle 3.5.

After some diffing with projects that were working correctly, I discovered that my `gradle-wrapper.properties` file was pointing to the Gradle 3.0 instead of 3.5 (see below).  Syncing these up at 3.5 resolved my issues.  If you're running in a multi-project environment where your projects have been upgraded over the years, double check your wrapper config in each project.  This starts breaking things at 3.3.9.

<img width="544" alt="Screen Shot 2019-07-31 at 10 17 09 PM" src="https://user-images.githubusercontent.com/3819936/62267529-30d83500-b3e1-11e9-83db-d7039d1898bb.png">

**Comment by zfree** [comment]
What fixed it for me was downgrading the `grails-gradle-plugin` in `build.gradle` changing:

```
classpath "org.grails:grails-gradle-plugin:$grailsVersion" // 3.3.10 in my case
```
to
```
classpath "org.grails:grails-gradle-plugin:3.3.8"
```
for both the app and the plugin.

**Comment by ppazos** [comment]
The issue for me was having Gradle 6.x installed form SKDMAN and a Grails 3.3.10 app. When I switched the Gradle version to 3.5 in SDKMAN, the Grails app worked as expected. It's an issue that working on a multi-version environment, we need to remember on which version of Gradle each app should build and run...
