### ISSUE TITLE
Grails 4 Plugin automatically hot swapping not working

### ISSUE THREAD

**Issue by hmtmcse** [grails/grails-core#11396]
### Task List

- [ ] Followed the create plugin instruction from https://docs.grails.org/4.0.0/guide/plugins.html
- [ ] Run the myapp project from Git bash cli , 
- [ ] Created new controller in myapp , when changing here it reloading perfectly
- [ ] Created new controller in  myplugin, when changing here it not reloading changes

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 4.0.0
- **JDK Version:** Oracle JDK 11 and also 8
- **Container Version (If Applicable):** Development Tomcat

### Example Application
https://github.com/hmtmcse/grails4-plugin-hot-reload

**Comment by jameskleeh** [comment]
In the plugin directory, add or modify the gradle.properties file. A new property exploded=true needs to be set in order for the plugin to add the exploded directories to the classpath.

**Comment by hmtmcse** [comment]
@jameskleeh Thank you so much, it's worked for me now, but i tried it with many way last 1 week, and whole week was painful, could you please add this into the plugin creation document, this will may help lots of people. Thanks again
