### ISSUE TITLE
Grails doesn't reload in Testing environment, even if reload is enabled through flags

### ISSUE THREAD

**Issue by joklek** [grails/grails-core#11422]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce

1. Create new project 
2. `grails run-app -Dgrails.reload.enabled=true -Dgrails.env=test`
3. Change any groovy file

### Expected Behaviour

After changing any groovy files, grails application should reload them

### Actual Behaviour

After changing any groovy files, grails application doesn't reload the classes.

On application initialization Environment::isReloadingAgentEnabled() returns false, as `Class.forName("org.springsource.loaded.TypeRegistry")` throws a `ClassNotFoundException`. It seems that the springloaded classes are not in the current classloader.

### Environment Information

- **Operating System**: Windows 10
- **Grails Version:** 3.3.9 - 3.3.11
- **JDK Version:** JDK 8

### Stacktrace
```
grails.util.Environment.isReloadingAgentEnabled(Environment.java:660)
grails.boot.config.GrailsApplicationPostProcessor.<clinit>(GrailsApplicationPostProcessor.groovy:55)
grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.groovy:68)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115)
org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:123)
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:666)
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:353)
org.springframework.boot.SpringApplication.run(SpringApplication.java:300)
grails.boot.GrailsApp.run(GrailsApp.groovy:84)
grails.boot.GrailsApp.run(GrailsApp.groovy:393)
grails.boot.GrailsApp.run(GrailsApp.groovy:380)
grails.boot.GrailsApp$run.call(Unknown Source)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
Application.main(Application.groovy:8)
```

**Comment by jameskleeh** [comment]
What is the use case to reload in the test environment? It is designed for running tests, where reloading would not be necessary or desired.

**Comment by joklek** [comment]
In our environment it sounds more logical to switch environment names, because of legacy reasons. Dev becomes test and test becomes dev. Are there any more side effects of switching them?

**Comment by jameskleeh** [comment]
@joklek There are likely several places in the framework that make the assumption test is for testing. I can't think of them without digging into it, however I would use a custom environment. I don't have any reason to believe a custom environment wouldn't work with reloading.

**Comment by joklek** [comment]
Roger that. Will try to experiment tomorrow. Thank you for the great responses!
