### ISSUE TITLE
issues with URL which has path params > 5

### ISSUE THREAD

**Issue by OptimusPrimeLogan** [grails/grails-core#11463]
I am upgrading my grails 2.2.4 [with spring-security-core:1.2.7.3] to grails 4.0.0 [spring-security-core:4.0.0.RC2]
I am having issues with one of the API URLs, wherethe  method have a multi-level path params[5 levels -  / */ */ */ */ *], those methods which has levels until 4 are working fine.
For those methods which have the level of 5, an error throws up in logs stating, NO Mapping for POST

Whereas If I generate a URL mapping report, I am able to see the mapping as
`|    *     | /api/y/z/*/*/*/*/*                                       | Action: (default action) |`

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)
- [ ] Example that reproduces the problem uploaded to Github

### Steps to Reproduce

1. Create a grails 4.0.0 [spring-security-core:4.0.0.RC2] application with a REST profile
2. Create a JAX-RS resource and create a method with path params higher than 4 levels [ /api/y/z/*/*/*/*/*]
3. Send an HTTP request to the API method

### Expected Behaviour

1. The request should go through the Spring Security Filters.
2. The DefaultUrlMappingsHolder matches the appropriate API method from the resource.
3. The method responds with data to the requested medium

### Actual Behaviour

1. The request facade gets validated by Spring Security and sent for the actual processing.
2. The DefaultUrlMappingsHolder attempting to match the request with cached request maps, although the [/api/y/z/*/*/*/*/*] is available in the cached request map, DefaultUrlMappingsHolder  fails to map [/api/y/z/param1/param2/param3/param4/param5]

`o.g.w.mapping.DefaultUrlMappingsHolder   : Attempting to match URI [/api/y/z/param1/param2/param3/param4/param5] with pattern [/api/y/z/*/*/*/*/*]`

`2020-01-16 13:52:44.644  WARN 15736 --- [nio-9090-exec-4] o.s.web.servlet.PageNotFound             : No mapping for POST /api/y/z/*/*/*/*/*`

### Environment Information

- **Operating System**: Windows 10 64 bit
- **Grails Version:** 4.0.0
- **JDK Version:** OpenJDK 11
- **IDE:** IntelliJ IDEA IDE | Version: 2019.3.1

**Comment by OptimusPrimeLogan** [comment]
Any feedback on this. Kindly let me know.

**Comment by puneetbehl** [comment]
I tried to replicate with the following resource which seems to work fine:
```
@Resource(uri='/api/x/y/z/books', formats = ['json', 'xml'])
class Book {

    String title

    static constraints = {
        title blank: false
    }
}

```

So, I would request you to please share a sample application.
