### ISSUE TITLE
"Could not resolve view" exceptions when executing a REST-API profile app via Runnable JAR with grails 4.0.5 and windows.

### ISSUE THREAD

**Issue by tircnf** [grails/grails-core#11655]
### Task List

- [x] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem downloaded from grails application forge.
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. grails create-app foobar --profile=rest-api
2. or
3. curl -O start.grails.org/foobar.zip -d version=4.0.5 -d profile=rest-api
4.  cd foobar ; grails war
5 java -jar myApp.war
6 curl localhost:8080

### Expected Behaviour

should get the "hello world" json response back.

### Actual Behaviour

Grails application running at http://localhost:8080 in environment: production

    2020-11-23 20:59:14.406 ERROR --- [nio-8080-exec-1] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'] with root cause
    
    javax.servlet.ServletException: Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1352)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)

### Environment Information

- **Operating System**: windows
- **Grails Version:** 4.0.5
- **JDK Version:** 1.8
- **Container Version (If Applicable):** none.  embedded tomcat.

### Example Application

curl -O start.grails.org/myapp.zip -d version=4.0.5 -d profile=rest-api
but the war is built on windows.

There are a bunch of tickets about this with grails 3 and one with grails 4.0.1.  

https://github.com/grails/grails-core/issues/9710
https://github.com/grails/grails-core/issues/9758
https://github.com/grails/grails-core/issues/11421

I have verified I have no spaces in my path to grails/gradle/source code.

I had a co-worker generate the same .war file on a mac and ran a diff on the file directories.  This was the only thing I could find. (with an app named "foobar").

In the working example (compiled on a mac)  the index classes have a single _ between the project name and the filename.
in the broken (compiled on windows) .war file the index classes have two underscores.

    $ diff  <(cd works; ls -R *) <(cd broken; ls -R *)
    110,126c110,126
    < foobar_application_index_gson$_run_closure1$_closure2.class
    < foobar_application_index_gson$_run_closure1$_closure3.class
    < foobar_application_index_gson$_run_closure1.class
    < foobar_application_index_gson.class
    < foobar_error_gson$_run_closure1.class
    < foobar_error_gson.class
    < foobar_errors__errors_gson$_run_closure1$_closure2$_closure4.class
    < foobar_errors__errors_gson$_run_closure1$_closure2.class
    < foobar_errors__errors_gson$_run_closure1$_closure3$_closure5$_closure6$_closure7.class
    < foobar_errors__errors_gson$_run_closure1$_closure3$_closure5$_closure6.class
    < foobar_errors__errors_gson$_run_closure1$_closure3$_closure5.class
    < foobar_errors__errors_gson$_run_closure1$_closure3.class
    < foobar_errors__errors_gson$_run_closure1.class
    < foobar_errors__errors_gson.class
    < foobar_notFound_gson$_run_closure1.class
    < foobar_notFound_gson.class
    < foobar_object__object_gson.class
    ---
    > foobar__application_index_gson$_run_closure1$_closure2.class
    > foobar__application_index_gson$_run_closure1$_closure3.class
    > foobar__application_index_gson$_run_closure1.class
    > foobar__application_index_gson.class
    > foobar__error_gson$_run_closure1.class
    > foobar__error_gson.class
    > foobar__errors__errors_gson$_run_closure1$_closure2$_closure4.class
    > foobar__errors__errors_gson$_run_closure1$_closure2.class
    > foobar__errors__errors_gson$_run_closure1$_closure3$_closure5$_closure6$_closure7.class
    > foobar__errors__errors_gson$_run_closure1$_closure3$_closure5$_closure6.class
    > foobar__errors__errors_gson$_run_closure1$_closure3$_closure5.class
    > foobar__errors__errors_gson$_run_closure1$_closure3.class
    > foobar__errors__errors_gson$_run_closure1.class
    > foobar__errors__errors_gson.class
    > foobar__notFound_gson$_run_closure1.class
    > foobar__notFound_gson.class
    > foobar__object__object_gson.class

**Comment by abrahaj** [comment]
Having the same issue. 
Building in Linux worked fine. Did not do a diff, but I assume it is the same. 
Tested on Grails 4.0.3 & 4.0.5
Also tested with views-gradle:2.0.3, views-gradle:2.0.2 & 2.0.0.RC2
It is strange because I had the issue before and I got it running to build on Windows somehow (views 2.0.0.RC2& Gradle 4.0.3)

**Comment by puneetbehl** [comment]
I think it would work when you run the WAR from project root directory as:
```
java -jar ./build/libs/myApp.war
```

**Comment by puneetbehl** [comment]
It seems to be fixed in Grails Views 2.0.3. Please update the version of the Grails View as follows in `build.gradle`:

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.name.startsWith("views-") {
            details.useVersion("2.0.3")
        }
    }
}

```
