### ISSUE TITLE
GSP double encoding prevention does not work as expected

### ISSUE THREAD

**Issue by flxtr** [grails/grails-core#11693]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided → no stracktrace thrown
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new Grails 4 app via IntelliJ IDEA
2. Create Controller: put two Strings  `amp1: '&amp;'` and `amp2: '&'.encodeAsHTML()` to the model
3. Create GSP-View: output each String with `${…}` and `${raw(…)}` and test the Strings in the view for equality.
4. don't change any default settings

### Expected Behaviour

- all outputs of the strings in the model are equal
- … exactly if `amp1 == amp2` is `true`

### Actual Behaviour

- `amp1 == amp2` is `true`, but
- `&{amp1}` outputs as `&amp;amp;` in the HTML source → shows up in the browser as "&amp;amp;"
- `&{amp2}` outputs as `&amp;`in the HTML source → shows up in the browser as "&"

<img src="https://user-images.githubusercontent.com/16322546/103831224-ec43d500-507b-11eb-8b65-5e2b9376ffa5.png" width="439px" alt="screenshot how it shows up in the browser, as described above">
<img src="https://user-images.githubusercontent.com/16322546/103831283-0e3d5780-507c-11eb-9109-99e123cbc535.png" width="311px" alt="screenshot how it shows up in the HTML source, as described above">

### Documentation to double encoding prevention:

> Grails 2.3 includes double encoding prevention so that when an expression is evaluated, it will not encode if the data has already been encoded (Example `${foo.encodeAsHTML()}`).

—https://docs.grails.org/latest/guide/security.html#_double_encoding_prevention

### Environment Information

- **Operating System**: Ubuntu 20.04
- **Grails Version:** 4.05
- **JDK Version:** 11.0.9.1
- **Container Version (If Applicable):** `./gradlew bootRun`

### Example Application

https://github.com/flxtr/gsp-double-encoding

*`DemoController.groovy`*
```
package gspdoubleencoding

class DemoController {

    def index() {
        def amp1 = '&amp;'
        def amp2 = '&'.encodeAsHTML()
        
        def model = [
                amp1: amp1,
                amp2: amp2
        ]

        render status: 200,
                model: model,
                view: 'demo'
    }
}

```

*`demo/demo.gsp`*
```
<p>${'$'}{amp1}: ${amp1}</p>
<p>${'$'}{raw(amp1)}: ${raw(amp1)}</p>
<p/>
<p>${'$'}{amp2}: ${amp2}</p>
<p>${'$'}{raw(amp2)}: ${raw(amp2)}</p>
<p/>
<p>
<g:if test="${amp1 == amp2}">
    amp1 == amp2
</g:if>
<g:else>
    amp1 != amp2
</g:else>
</p>
```

**Comment by flxtr** [comment]
Ok, I found out there is an `EncodingStateRegistry` where `CharSequence` objects get registered when encoded via the Grails infrastructure, right?

```
package org.grails.encoder;

/**
 * EncodingStateRegistry keeps encoding state of CharSequence instances.
 * Encoding state information is required for the solution that prevents
 * double-encoding a value that is already encoded. In the current
 * implementation, a single EncodingStateRegistry instance is bound to a HTTP
 * request life cycle.
 *
 * @author Lari Hotari
 * @since 2.3
 */
public interface EncodingStateRegistry {
[…]
```

I see, that its the `encodeAs…()` calls which are protected against double encoding, not exclusive in GSPs as implied in the docs.
So:
```
def amp = '&'.encodeAsHTML()
assert amp == '&amp;'
assert amp.encodeAsHTML() == '&amp;' 
```
But:
```
def amp = new String('&'.encodeAsHTML() as char[])
assert amp == '&amp;'
assert amp.encodeAsHTML() == '&amp;amp;' 
```

Due to the docs I assumed, the encoding in GSPs would be kind of automagically prevent any full or partially HTML encoded Strings/CharSquences from being double encoded. But that’s not how this works. So I'll close.
