### ISSUE TITLE
Run status shows wrong protocol in URL if server.ssl.key-store is set via app config

### ISSUE THREAD

**Issue by douglyuckling** [grails/grails-core#11732]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided (N/A)
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided

### Steps to Reproduce

1. Configure `server.ssl.key-store` via an application config file such as `application.yml`. (Of course it needs to point to a valid keystore file.)
2. Also configure `server.ssl.key-store-password` and `server.ssl.key-password` as appropriate so that the keystore can be read, though this does not necessarily need to be done via application config.
3. Run `grails run-app` (without the `-https` option)

### Expected Behaviour

When the app is finished starting, Grails should report that the app is running at a URL beginning with `https://`.

### Actual Behaviour

Grails reports that the app is running at a URL beginning with `http://`. The URL does not work because the app is in fact listening for HTTPS connections.

### Environment Information

- **Operating System**: Any
- **Grails Version**: At least 3.3.x and 4.0.x, but probably others as well.
- **JDK Version**: Any
- **Container Version (If Applicable)**: N/A

### Example Application

- Grails 4.0.x: https://github.com/douglyuckling/grails-run-status-protocol-bug/tree/grails-4.0.x
- Grails 3.3.x: https://github.com/douglyuckling/grails-run-status-protocol-bug/tree/grails-3.3.x

**Comment by douglyuckling** [comment]
The bug is simple to fix, and I plan to submit pull requests for the 3.3.x and 4.0.x branches.

**Comment by douglyuckling** [comment]
I should also mention that the README.md in the example repos do have a brief explanation of the cause of the bug.

**Comment by douglyuckling** [comment]
I created pull requests for the 3.3.x branch and the 4.0.x branch.

The build for the 4.0.x branch looks to have failed for a reason unrelated to my change, so hopefully someone can get that resolved. (The tests passed, but publishing the test results failed.)

The build for the 3.3.x branch is supposedly still queued in Travis CI as of now.
