### ISSUE TITLE
[3.3.11] Controller redirect appends URL to existing URL

### ISSUE THREAD

**Issue by jmccordova** [grails/grails-core#11741]
### Task List

- [X ] Steps to reproduce provided
- [] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Download Grails v3.3.2
2. Clean, Compile, Run application
3. Verify running
4. Create a link with a "redirect action:''" directive
5. Click link
6. Verify if redirection happens
7. Stop application
8. Open gradle.properties
9. Change grailsVersion to 3.3.11
10. Repeat step 2 and 6

### Expected Behaviour

Redirection happens without a problem

### Actual Behaviour

- Returns a 404 error
- redirect appends a URL to existing URL
![Grails 3 3 11 redirect error](https://user-images.githubusercontent.com/3425512/108298556-260a0e80-71d8-11eb-90e5-607d66371187.png)

### Environment Information

- **Operating System**: Windows 10 20H2
- **Grails Version:** 3.3.11
- **JDK Version:** 1.8.0_281
- **Container Version (If Applicable):** None

### Example Application

- [Get it here](https://sourceforge.net/projects/ro3-pos/).

**Comment by jmccordova** [comment]
Update:

For some reason, it's working now. What I did was play with grailsVersion. I started looking for a more update version wherein redirection works correctly. For me, it was 3.3.6.

Then, I switched back to 3.3.11 and it's working like nothing happened.

Any thoughts on why this happened?

**Comment by jeffbrown** [comment]
Why is it that you would execute `redirect action:''`?
