### ISSUE TITLE
5.0.0.RC2 Bugs

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-core#12049]
### Task List

- [ ] "org.hibernate:hibernate-core:5.5.7" dependency does not exist.
- [ ] Executable wars and jars do not have access to plugin resources.
- [ ] Resource Controllers Render as Content-Type: application/xhtml 

# 5.5.7 dependency does not exist.
```
sdk use grails 5.0.0.RC2
grails create-app website
```
Results in 

https://github.com/codeconsole/website/blob/master/build.gradle#L57
```implementation "org.hibernate:hibernate-core:5.5.7"```

which does not exist 
https://repo.maven.apache.org/maven2/org/hibernate/hibernate-core/

It should be 5.5.7.Final

# Executable wars and jars do not have access to plugin resources.

See https://github.com/grails/grails-core/issues/11999
Sample app https://github.com/codeconsole/grails4bugs has been updated to 5.0.0.RC2 to demonstrate the issue

# Resource Controllers to Render as Content-Type: application/xhtml 

See https://github.com/grails/gorm-hibernate5/issues/303
Sample app https://github.com/codeconsole/gormbug has been updated to 5.0.0.RC2 to demonstrate the issue
