### ISSUE TITLE
grails 3.1.5 Spring not scanning some packages after war deployment

### ISSUE THREAD

**Issue by JohnTheBeloved** [grails/grails-core#9942]
Grails 3 does not scan packages I specify in the application.yml files

spring:
        bean:
            packages:
              - my.first.package
              - my.second.package

, not after i have to add `@ComponentScan(value=['my.first.package','my.second.package'])` to the Applicaion.groovy file

Some of the Beans are not created due to this, especially of dependencies and files in my src folder

### Task List
- [x] Add an External Dependency that has some declared beans to an existing project
- [x] Grails runs fine during development run (grails run-app), but not when deployed with the war
- [x] Error thrown about some beans not existing whereas, Spring didn't scan those packages for beans on startup 

### Steps to Reproduce

 
- **Operating System**: Windows
- **Grails Version:** grails 3.1.5
- **JDK Version:** jdk 1.8.0_77-b03

**Comment by JohnTheBeloved** [comment]
I am very sorry for this

Found the Solution in the Documentation where grails will scan artifact directories by default, i'll have to override this method in the Application class

```
class Application extends GrailsAutoConfiguration {
    @Override
    Collection<String> packageNames() {
        super.packageNames() + ['my.additional.package']
    }
    …
}
```

http://grails.github.io/grails-doc/3.0.x/api/grails/boot/config/GrailsAutoConfiguration.html
